### ISSUE TITLE
websitescreenshot is not work

### ISSUE THREAD

**Issue by mikeorlovdesign** [tgjones/dynamic-image#22]
websitescreenshot is not work, on your website too.
Can you fix it please?
http://dynamicimage.apphb.com/extensions/websitescreenshot

**Comment by tgjones** [comment]
It turns out that the `Timeout` property was just set too low. I haven't changed the default timeout for  `WebsiteScreenshotLayer` (5 seconds), but I have increased the timeout on the examples website from 3 seconds to 15 seconds. This appears to be enough to make it work on AppHarbor. It's likely that you're experiencing the same issue.

Fixed by d88a907 and 5063a37.
