### ISSUE TITLE
Windows Service

### ISSUE THREAD

**Issue by 304NotModified** [tgjones/dynamic-image#26]
Hi,

Are Windows services also supported?

**Comment by tgjones** [comment]
It's a good question. In theory, yes, because DynamicImage never creates a visible UI control - that's how DynamicImage is able to work on servers. But I haven't tested it in a Windows service context. If you encounter any problems, please re-open this issue and I'll take a look.

**Comment by 304NotModified** [comment]
Are there any dependencies  to asp.net in this lib?

**Comment by tgjones** [comment]
There are, but that shouldn't be a problem, as long as you don't try to use caching, which would require an ASP.NET HTTP context.

You can create a `Composition`, as described on this page:
http://dynamicimage.apphb.com/gettingstarted/fluentapi

If you use `CompositionBuilder`, you can call `GetImage()` or `SaveTo()`, but not `.Url`, because the latter wouldn't work without an HTTP context.
